version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: America/New_York
      ignored_updates:
      - match:
          dependency_name: "core-js"
          dependency_name: "@babel*"
      automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:patch"
    open-pull-requests-limit: 20
